# Generated by Django 6.0.3 on 2026-04-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_icon'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'display_order', 'name'], name='cat_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='cat_created_idx'),
        ),
    ]
