# Generated by Django 6.0.3 on 2026-03-31 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='lessons.lesson'),
        ),
    ]
