# Generated by Django 6.0.3 on 2026-04-02 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_icon'),
        ('challenges', '0002_initial'),
        ('lessons', '0003_alter_lesson_options_lesson_created_at_lesson_order_and_more'),
        ('modules', '0003_module_estimated_time_module_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='categories.category'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='modules.module'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='lessons.lesson'),
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('lesson__isnull', False), ('module__isnull', True)), models.Q(('category__isnull', True), ('lesson__isnull', True), ('module__isnull', False)), models.Q(('category__isnull', False), ('lesson__isnull', True), ('module__isnull', True)), _connector='OR'), name='challenge_exactly_one_owner'),
        ),
    ]
