# Generated by Django 6.0.3 on 2026-04-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_time_limit_minutes_challengeattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
