# Generated by Django 6.0.3 on 2026-04-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challengequestion_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestion',
            name='correct_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='numeric_tolerance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True / False'), ('numeric', 'Numeric'), ('short_text_strict', 'Short Text (Strict)')], default='short_text_strict', max_length=30),
        ),
    ]
