# Generated by Django 6.0.3 on 2026-04-04 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_cat_active_order_idx_and_more'),
        ('challenges', '0008_challenge_created_at'),
        ('lessons', '0004_lesson_lesson_module_title_idx_and_more'),
        ('modules', '0005_module_module_cat_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['difficulty', 'created_at'], name='challenge_diff_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['created_at'], name='challenge_created_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesubmission',
            index=models.Index(fields=['user', 'submitted_at'], name='csub_user_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='challengesubmission',
            index=models.Index(fields=['challenge', 'submitted_at'], name='csub_chal_submitted_idx'),
        ),
    ]
