# Generated by Django 6.0.3 on 2026-08-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_challenge_is_daily_and_owner_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengequestion',
            name='correct_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
