# Generated by Django 6.0.3 on 2026-04-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_remove_notification_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRetentionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Retention Setting',
                'verbose_name_plural': 'Notification Retention Setting',
            },
        ),
    ]
