# Generated by Django 6.0.3 on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_challenge_is_daily_and_owner_rule'),
        ('daily_challenge', '0002_dailychallenge_inherit_challenge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailychallenge',
            options={},
        ),
        migrations.RemoveField(
            model_name='dailychallenge',
            name='challenge_ptr',
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='challenge',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='daily_profile',
                to='challenges.challenge',
            ),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
