# Generated by Django 6.0.3 on 2026-03-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdailyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('learner', 'Learner')], default='learner', max_length=20),
        ),
    ]
