# Generated by Django 6.0.3 on 2026-04-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
