# Generated by Django 6.0.3 on 2026-04-03 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_challenge_created_at'),
        ('lessons', '0003_alter_lesson_options_lesson_created_at_lesson_order_and_more'),
        ('modules', '0003_module_estimated_time_module_prerequisites'),
        ('progress', '0002_userprogress_progress_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_parts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='modules.module'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_parts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='challenges.challenge'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('challenge__isnull', False), ('lesson__isnull', True), ('module__isnull', True)), models.Q(('challenge__isnull', True), ('lesson__isnull', False), ('module__isnull', True)), models.Q(('challenge__isnull', True), ('lesson__isnull', True), ('module__isnull', False)), _connector='OR'), name='progress_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('challenge__isnull', False)), fields=('user', 'challenge'), name='unique_user_challenge_progress'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', False)), fields=('user', 'lesson'), name='unique_user_lesson_progress'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('module__isnull', False)), fields=('user', 'module'), name='unique_user_module_progress'),
        ),
    ]
