# Generated by Django 6.0.3 on 2026-04-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_userprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
