# Generated by Django 6.0.3 on 2026-04-04 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_challenge_challenge_diff_ct_idx_and_more'),
        ('lessons', '0004_lesson_lesson_module_title_idx_and_more'),
        ('modules', '0005_module_module_cat_created_idx_and_more'),
        ('progress', '0004_userprogress_created_at_userprogress_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'updated_at'], name='uprogress_user_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'completed'], name='uprogress_user_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['updated_at'], name='uprogress_updated_idx'),
        ),
    ]
