# Generated by Django 6.0.3 on 2026-03-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_module_level_module_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='estimated_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated time to complete in minutes'),
        ),
        migrations.AddField(
            model_name='module',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Modules that must be completed before this one', related_name='dependent_modules', to='modules.module'),
        ),
    ]
