# Generated by Django 6.0.3 on 2026-04-04 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_cat_active_order_idx_and_more'),
        ('modules', '0004_moduleenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['category', 'created_at'], name='module_cat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['category', 'updated_at'], name='module_cat_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleenrollment',
            index=models.Index(fields=['user', 'enrolled_at'], name='mod_enroll_user_time_idx'),
        ),
    ]
