# Generated by Django 6.0.3 on 2026-04-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_cat_active_order_idx_and_more'),
        ('lessons', '0003_alter_lesson_options_lesson_created_at_lesson_order_and_more'),
        ('modules', '0005_module_module_cat_created_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'title'], name='lesson_module_title_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'updated_at'], name='lesson_module_upd_idx'),
        ),
    ]
